[workspace]

resolver = "2"

members = [
    "powdr",
    "powdr-test",
    "number",
    "parser",
    "cli",
    "executor",
    "riscv",
    "parser-util",
    "pil-analyzer",
    "pipeline",
    "pilopt",
    "plonky3",
    "asm-to-pil",
    "halo2",
    "backend",
    "ast",
    "analysis",
    "linker",
    "asm-utils",
    "airgen",
    "riscv-executor",
    "schemas",
]

exclude = [ "riscv-runtime" ]

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT"
homepage = "https://powdr.org"
repository = "https://github.com/powdr-labs/powdr"

[profile.pr-tests]
inherits = "dev"
opt-level = 3
debug = "line-tables-only"
debug-assertions = true
overflow-checks = true
panic = 'unwind'
incremental = true         # This is true because target is cached
codegen-units = 256

# This can be removed when upgrading to the next release of Halo2, because this has been merged:
# https://github.com/privacy-scaling-explorations/halo2/pull/292
[patch."https://github.com/privacy-scaling-explorations/halo2"]
halo2_proofs = { git = "https://github.com/georgwiese/halo2", branch = "make-emit-public-v0.3.0", features = ["circuit-params"] }