[package]
name = "plonky3"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "0d6a492" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3.git", rev = "0d6a492" }
powdr-ast = { version = "0.1.0-alpha.1", path = "../ast" }
powdr-number = { version = "0.1.0-alpha.1", path = "../number" }
