[package]
name = "powdr-plonky3"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3-air = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3.git" }
powdr-ast = { version = "0.1.0-alpha.1", path = "../ast" }
powdr-number = { version = "0.1.0-alpha.1", path = "../number" }
p3-field = { git = "https://github.com/Plonky3/Plonky3.git" }
rand = "0.8.5"

[dev-dependencies]
p3-uni-stark = { git = "https://github.com/Plonky3/Plonky3.git" }
powdr-airgen = { path = "../airgen" }
powdr-analysis = { path = "../analysis" }
powdr-executor = { path = "../executor" }
powdr-importer = { path = "../importer" }
powdr-linker = { path = "../linker" }
powdr-parser = { path = "../parser" }
powdr-pipeline = { path = "../pipeline" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3.git", features = ["test-utils"] }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-circle = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-fri = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-keccak = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-mds = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-merkle-tree = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-mersenne-31 = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-dft = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-challenger = { git = "https://github.com/Plonky3/Plonky3.git" }
p3-util = { git = "https://github.com/Plonky3/Plonky3.git" }
